name=Logger
version=1.0.0
author=Ferenc Mayer <dynapptor@dynapptor.com>
sentence=Lightweight and flexible logging library for Arduino.
paragraph=Supports logging to Serial or any Stream, with customizable log levels and callback handling. Designed for performance and easy integration.
category=Communication
url=https://github.com/dynapptor/Logger
architectures=*
includes=Logger.h

